# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(973, 785)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 931, 651))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(5, 3, 3, 0)
        self.horizontalLayout.setSpacing(3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.choosenImgLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.choosenImgLabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.choosenImgLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.choosenImgLabel.setObjectName("choosenImgLabel")
        self.horizontalLayout.addWidget(self.choosenImgLabel)
        self.myTabWidget = QtWidgets.QTabWidget(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.myTabWidget.sizePolicy().hasHeightForWidth())
        self.myTabWidget.setSizePolicy(sizePolicy)
        self.myTabWidget.setObjectName("myTabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.OCROut = QtWidgets.QLabel(self.tab)
        self.OCROut.setGeometry(QtCore.QRect(0, 0, 451, 621))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OCROut.sizePolicy().hasHeightForWidth())
        self.OCROut.setSizePolicy(sizePolicy)
        self.OCROut.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.OCROut.setAutoFillBackground(True)
        self.OCROut.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.OCROut.setObjectName("OCROut")
        self.myTabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.myTabWidget.addTab(self.tab_2, "")
        self.horizontalLayout.addWidget(self.myTabWidget)
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(700, 650, 221, 80))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.doOCRButton = QtWidgets.QPushButton(self.formLayoutWidget)
        self.doOCRButton.setObjectName("doOCRButton")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.doOCRButton)
        self.langCombo = QtWidgets.QComboBox(self.formLayoutWidget)
        self.langCombo.setObjectName("langCombo")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.langCombo)
        self.languageLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.languageLabel.setObjectName("languageLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.languageLabel)
        self.pickFileButton = QtWidgets.QPushButton(self.centralwidget)
        self.pickFileButton.setGeometry(QtCore.QRect(370, 660, 91, 31))
        self.pickFileButton.setObjectName("pickFileButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 973, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.myTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.choosenImgLabel.setText(_translate("MainWindow", "The choosen image will be shown here"))
        self.OCROut.setText(_translate("MainWindow", "The output of the automatic text detectionwill be shown here"))
        self.myTabWidget.setTabText(self.myTabWidget.indexOf(self.tab), _translate("MainWindow", "Ocr result"))
        self.myTabWidget.setTabText(self.myTabWidget.indexOf(self.tab_2), _translate("MainWindow", "Extracted keywords"))
        self.doOCRButton.setText(_translate("MainWindow", "Extract text"))
        self.languageLabel.setText(_translate("MainWindow", "Choose a language :"))
        self.pickFileButton.setText(_translate("MainWindow", "Pick a file"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
